version: '3.8'
services:
  app:
    build: .
    image: ashishworld/yii2-app:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: yii2app
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
