- hosts: web
  become: yes
  tasks:
    - name: Install Docker, NGINX, Git
      apt:
        name:
          - docker.io
          - nginx
          - git
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Initialize Docker Swarm
      shell: docker swarm init
      ignore_errors: yes

    - name: Copy NGINX config
      copy:
        src: ./nginx/yii2
        dest: /etc/nginx/sites-available/yii2
        mode: 0644

    - name: Enable NGINX config
      file:
        src: /etc/nginx/sites-available/yii2
        dest: /etc/nginx/sites-enabled/yii2
        state: link
        force: yes

    - name: Reload NGINX
      shell: nginx -t && systemctl reload nginx

    - name: Deploy Yii2 Stack
      shell: docker stack deploy -c /home/ubuntu/yii2-app/docker-compose.yml yii2app
