- hosts: web
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - nginx
          - php8.1
          - php8.1-fpm
          - git
        update_cache: yes

    - name: Start docker
      systemd:
        name: docker
        enabled: yes
        state: started
