- hosts: web
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - nginx
          - git
          - php8.1-fpm
        update_cache: yes

    - name: Start Docker and PHP-FPM
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - docker
        - php8.1-fpm

    - name: Initialize Docker Swarm
      shell: docker swarm init
      ignore_errors: true

    - name: Copy docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Deploy Docker stack
      shell: docker stack deploy -c /home/ubuntu/docker-compose.yml yii2app
