name: Deploy Yii2 to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/yii2-app
            git pull origin main
            docker build -t ashishworld/yii2-app:latest .
            docker push ashishworld/yii2-app:latest
            docker service update --image ashishworld/yii2-app:latest yii2app_app
